name: parkingster
description: "Parking reservation."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^4.0.2
  google_maps_flutter: ^2.9.0
  graphql_flutter: ^5.2.0-beta.7
  http: ^1.2.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  location: ^6.0.2
  package_info_plus: ^8.0.2
  permission_handler: ^11.3.1
  provider: ^6.1.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
